name = "internship-matching"
main = ".open-next/worker.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_ALLOWED_EMAIL_DOMAIN = "kamiyama.ac.jp"
